# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ./actions.h \
    ./application.h \
    ./reportdesigner.h \
    ./reportview.h \
    ./workbench.h
SOURCES += ./actions.cpp \
    ./application.cpp \
    ./main.cpp \
    ./reportdesigner.cpp \
    ./reportview.cpp \
    ./workbench.cpp
RESOURCES += ./reportdesigner.qrc
